-- CreateEnum
CREATE TYPE "STATUS" AS ENUM ('UPCOMING', 'ONGOING', 'FINISHED');

-- AlterTable
ALTER TABLE "Exam" ADD COLUMN     "status" "STATUS" NOT NULL DEFAULT E'UPCOMING',
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "description" DROP DEFAULT;
